# Generated by Django 3.1.2 on 2020-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
